#
# Copyright (c) 2021 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_GZLL=y
CONFIG_GAZELL=y

# --- UART ---
CONFIG_SERIAL=y
CONFIG_PRINTK=y

# --- Threading ---
CONFIG_IDLE_STACK_SIZE=512

# --- Power management ---
CONFIG_NRFX_POWER=y

# --- Real-time Clock ---
CONFIG_NRFX_RTC0=y
CONFIG_NRFX_RTC1=y

# --- Logging ---
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_BACKEND_UART=y

# --- Debugging ---
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_DEBUG=y